import { type NextPage } from "next";
import Head from "next/head";
import MainLayout from "../components/layout/MainLayout";
import Dashboard from "../components/dashboard/Dashboard";
import { useSession } from "next-auth/react";
import Loading from "../components/layout/Loading";
import { useEffect } from "react";
import { useRouter } from "next/router";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const { status } = useSession();
  const router = useRouter();

  useEffect(() => {
    if (status === "unauthenticated") router.push("/login");
  }, [status, router]);

  if (status === "loading") return <Loading />;

  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <Dashboard />
      </MainLayout>
    </>
  );
};

export default Home;
